import {
  Home,
  Package,
  Settings,
  AlertTriangle,
  Loader2,
  XCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Wifi,
  WifiOff,
  Clock,
  Sparkles,
  Search,
  ArrowLeft,
  Info,
  Filter,
  Star,
  Share2,
  CheckCircle,
  AlertTriangle as AlertTriangleIcon,
  Truck,
  Award,
  Target,
  Box,
  X,
  Beer,
  Wine,
  GlassWater,
  Droplets,
  Zap,
  CupSoda,
  Newspaper,
  ReceiptText,
  ChevronUp,
  Tag,
  FolderOpen,
  Download,
  Image,
  FileText,
  Palette,
  Grid3x3,
  LayoutGrid,
  Eye,
  Camera,
  Megaphone,
  BookOpen,
  Bookmark,
  DollarSign,
  MessageCircle,
  Briefcase,
  type LucideIcon
} from 'lucide-react';

// Map of icon names to Lucide components
const iconMap: Record<string, LucideIcon> = {
  home: Home,
  package: Package,
  settings: Settings,
  alertTriangle: AlertTriangle,
  loader: Loader2,
  xCircle: XCircle,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  wifi: Wifi,
  wifiOff: WifiOff,
  clock: Clock,
  sparkles: Sparkles,
  search: Search,
  arrowLeft: ArrowLeft,
  info: Info,
  filter: Filter,
  star: Star,
  share2: Share2,
  checkCircleIcon: CheckCircle,
  alertTriangleIcon: AlertTriangleIcon,
  truck: Truck,
  award: Award,
  target: Target,
  box: Box,
  x: X,
  beer: Beer,
  wine: Wine,
  glassWater: GlassWater,
  droplets: Droplets,
  zap: Zap,
  cupSoda: CupSoda,
  newspaper: Newspaper,
  receiptText: ReceiptText,
  tag: Tag,
  folderOpen: FolderOpen,
  download: Download,
  image: Image,
  fileText: FileText,
  palette: Palette,
  grid3x3: Grid3x3,
  eye: Eye,
  camera: Camera,
  megaphone: Megaphone,
  layoutGrid: LayoutGrid,
  bookOpen: BookOpen,
  chevronLeft: ChevronLeft,
  bookmark: Bookmark,
  dollarSign: DollarSign,
  messageCircle: MessageCircle,
  briefcase: Briefcase,
};

export interface IconProps {
  name: keyof typeof iconMap;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 24, className = '', strokeWidth = 2 }: Readonly<IconProps>) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <IconComponent
      size={size}
      className={className}
      strokeWidth={strokeWidth}
    />
  );
}

// Re-export all icons for direct usage
export {
  Home,
  Package,
  Settings,
  AlertTriangle,
  Loader2,
  XCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Wifi,
  WifiOff,
  Clock,
  Sparkles,
  Search,
  ArrowLeft,
  Info,
  Filter,
  Star,
  Share2,
  CheckCircle,
  AlertTriangle as AlertTriangleIcon,
  Truck,
  Award,
  Target,
  Box,
  X,
  Beer,
  Wine,
  GlassWater,
  Droplets,
  Zap,
  CupSoda,
  Newspaper,
  ReceiptText,
  Tag,
  FolderOpen,
  Download,
  Image,
  FileText,
  Palette,
  Grid3x3,
  Eye,
  Camera,
  Megaphone,
  LayoutGrid,
  BookOpen,
  ChevronLeft,
  Bookmark,
  DollarSign,
  MessageCircle,
  Briefcase,
} from 'lucide-react';
